version: "3.8"
# docker stack deploy -c mongo.yml mongo
# Repair database: docker run -it -v <path>:/data/db <image-name> mongod --repair
#              eg: docker run -it -v ../databases/mongo:/data/db  mongo:4.4.8 mongod --repair

# Mongo DB
services:
  mongo:
    image: mongo:4.4.8
    hostname: mongo_host
    ports:
      - 27017:27017
    volumes:
      - ../databases/mongo:/data/db
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: America/Costa_Rica
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: root
#    networks:
#      #- bridge
#      #- app-tier

