version: "3.1"

#networks:
#  app-tier:
#    driver: bridge

# Mongo DB
services:
  mongo:
    # image: mongo
    image: mongo:4.4.8
    # command: mongod --port 27017
    # command: mongod --repair
    hostname: mongo_host
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: America/Costa_Rica
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: root
#    networks:
#      #- bridge
#      #- app-tier

