version: "3.1"

# Mongo DB
services:
  mongo:
    image: mongo
    hostname: mongo_host
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: America/Costa_Rica
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: root
