version: "3.8"
# docker stack deploy -c plex.yml plex
# docker stack remove plex
# docker compose -f plex.yml run plex -d
# <your-ip>:32400/web
# https://hub.docker.com/r/plexinc/pms-docker
# (*) Allow docker access to the files repository

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    # network_mode: host
    environment:
      - TZ=America/Costa_Rica
      - PLEX_CLAIM=claim-TOKEN
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ../databases/plex/library:/config
      - ../databases/plex/transcode:/transcode
    restart: unless-stopped
