version: "3.1"

# Postgre
services:
  postgres:
    image: postgres:13.5
    # hostname: postgres_host
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: America/Costa_Rica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
