version: "3.1"

# Postgre
services:
  postgre:
    image: postgres
    hostname: postgres_host
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: Etc/GMT+6 # America/Costa_Rica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /Volumes/Documents/docker/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
