version: "3.8"
# docker stack deploy -c postgres.yml postgres

services:
  postgres:
    image: postgres:13.5
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      TZ: America/Costa_Rica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../databases/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
