version: "3.0"

services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit_host"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SMOCKINGISNOTGOODFORUS"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: # make sure directories exists
      - "./rabbitmq-data/data:/var/lib/rabbitmq"
      - "./rabbitmq-data/logs:/var/log/rabbitmq"
    # - "./rabbitmq-data/etc:/etc/rabbitmq"

#
# CLUSTER START HERE
#
#  # First slave rabbitmq
#  rabbit2:
#    image: rabbitmq:3-management
#    hostname: rabbitmq_slave1
#    links:
#      - rabbitmq_master
#    environment:
#      - CLUSTERED=true
#      - CLUSTER_WITH=rabbitmq_master
#      - RAM_NODE=true
#    ports:
#      - "5673:5672"
#      - "15673:15672"
#
#  # Second slave rabbitmq
#  rabbit3:
#    image: rabbitmq:3-management
#    hostname: rabbitmq_slave2
#    links:
#      - rabbitmq_master
#      - rabbitmq_slave1
#    environment:
#      - CLUSTERED=true
#      - CLUSTER_WITH=rabbitmq_master
#    ports:
#      - "5674:5672"
