
version: "3.1"
# https://www.cloudsavvyit.com/10259/how-to-create-your-own-private-docker-registry/
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.key
    restart: always
    volumes:
      - ./certs:/certs
      #- ./auth:/auth
      - ./data:/data



